### ISSUE TITLE
no module named flask found

### ISSUE THREAD

**Issue by Jupiters-Father** [Grub4K/batChat#3]
I Was Going to use this i have typed pip install flask and it worked just fine it was when i started run.bat it keeps say no module named flask found

**Comment by exrodev** [comment]
Try just running `py server.py` and see if it works.

**Comment by Grub4K** [comment]
You need to install the [flask](https://github.com/pallets/flask) module before being able to use the server: [Installation guide](https://flask.palletsprojects.com/en/2.2.x/installation/).
